name: CI

# Trigger the workflow on push or pull request, but only for the main branch
on:
  pull_request:
  push:
    branches: [main]

jobs:
  cabal:
    name: ${{ matrix.os }} / ghc ${{ matrix.ghc }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
        cabal:
          - latest
        ghc:
          - "9.0.1"

    steps:
    - name: Checkout commit
      uses: actions/checkout@v2
      if: github.event.action == 'opened' || github.event.action == 'synchronize' || github.event.ref == 'refs/heads/main'

    - name: Set up GHC & cabal
      uses: haskell/actions/setup@v1
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}

    - name: Build ghc-tcplugin-api
      run: cabal build ghc-tcplugin-api

    - name: Build and lint System F example
      working-directory: ./examples/SystemF
      run: cabal build system-f
