name: CI

# Trigger the workflow on push or pull request, but only for the main branch
on:
  pull_request:
  push:
    branches: [main]

jobs:
  cabal:
    name: ${{ matrix.cfg.os }} / ghc ${{ matrix.cfg.ghc }}
    runs-on: ${{ matrix.cfg.os }}
    strategy:
      matrix:
        cfg:
          - { os: ubuntu-latest  , ghc: "9.2.1"  }
          - { os: ubuntu-latest  , ghc: "9.0.1"  }
          - { os: ubuntu-latest  , ghc: "8.10.6" }
          - { os: ubuntu-latest  , ghc: "8.8.4"  }
          - { os: macOS-latest   , ghc: "latest" }
          - { os: windows-latest , ghc: "latest" }

    steps:
    - name: Checkout commit
      uses: actions/checkout@v2
      if: github.event.action == 'opened' || github.event.action == 'synchronize' || github.event.ref == 'refs/heads/main'

    - name: Set up GHC & cabal
      uses: haskell/actions/setup@v1
      with:
        ghc-version: ${{ matrix.cfg.ghc }}
        cabal-version: ${{ matrix.cfg.cabal }}

    - name: Build ghc-tcplugin-api
      run: cabal build ghc-tcplugin-api

    - name: Build and lint System F example
      # Skip this test on GHC 8.8.4: we need StandaloneKindSignatures.
      if: matrix.cfg.ghc != '8.8.4'
      working-directory: ./examples/SystemF
      run: cabal build system-f
